/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GoogleDriveSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  serverRelayUrl: "http://localhost:5050",
  accessToken: "",
  refreshToken: "",
  tokenExpiry: 0,
  userEmail: "",
  vaultName: "DefaultVault",
  vaultFolderId: "",
  deviceId: `device_${Math.random().toString(36).substring(2, 9)}`,
  lastSyncTime: null,
  lastSyncStatus: "unauthenticated",
  customIgnoredPatterns: [],
  pendingOfflineChanges: [],
  syncedFileHashes: {}
};

// src/gdrive/gdriveAuth.ts
var import_obsidian = require("obsidian");
var GDriveAuth = class {
  constructor(getSettings, saveSettings) {
    this.getSettings = getSettings;
    this.saveSettings = saveSettings;
  }
  /**
   * Returns a valid access token. If token is near expiration (within 5 minutes) or expired,
   * automatically triggers a proactive refresh before returning.
   */
  async getValidAccessToken() {
    const settings = this.getSettings();
    if (!settings.accessToken) {
      throw new Error("Google Drive is not authenticated. Please log in or enter a pairing code in plugin settings.");
    }
    const now = Date.now();
    const isExpiringSoon = settings.tokenExpiry && now >= settings.tokenExpiry - 5 * 60 * 1e3;
    if (isExpiringSoon && settings.refreshToken) {
      await this.refreshAccessToken();
    }
    return this.getSettings().accessToken;
  }
  /**
   * Refreshes the Google OAuth access token using the stored refresh_token.
   */
  async refreshAccessToken() {
    const settings = this.getSettings();
    if (!settings.refreshToken) return false;
    try {
      const relayUrl = settings.serverRelayUrl.replace(/\/+$/, "");
      const response = await (0, import_obsidian.requestUrl)({
        url: `${relayUrl}/api/auth/google/refresh`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refreshToken: settings.refreshToken }),
        throwResponseError: false
      });
      if (response.status === 200) {
        const data = response.json;
        settings.accessToken = data.accessToken;
        if (data.expiryDate) {
          settings.tokenExpiry = data.expiryDate;
        } else {
          settings.tokenExpiry = Date.now() + 3600 * 1e3;
        }
        await this.saveSettings();
        return true;
      }
    } catch (err) {
      console.warn("Failed to refresh Google OAuth token:", err);
    }
    return false;
  }
  /**
   * Redeems a 6-digit pairing code to link this device.
   */
  async redeemPairingCode(code) {
    const settings = this.getSettings();
    const relayUrl = settings.serverRelayUrl.replace(/\/+$/, "");
    const response = await (0, import_obsidian.requestUrl)({
      url: `${relayUrl}/api/pair/${encodeURIComponent(code.trim())}`,
      method: "GET",
      headers: { "Content-Type": "application/json" },
      throwResponseError: false
    });
    if (response.status === 200) {
      const data = response.json;
      settings.accessToken = data.accessToken;
      if (data.refreshToken) settings.refreshToken = data.refreshToken;
      if (data.expiryDate) settings.tokenExpiry = data.expiryDate;
      if (data.userEmail) settings.userEmail = data.userEmail;
      if (data.vaultName) settings.vaultName = data.vaultName;
      if (data.vaultFolderId) settings.vaultFolderId = data.vaultFolderId;
      settings.lastSyncStatus = "up-to-date";
      await this.saveSettings();
      return true;
    }
    const errorJson = response.json || {};
    throw new Error(errorJson.error || `Pairing failed (HTTP ${response.status})`);
  }
  /**
   * Generates a 6-digit pairing code on this device to share with another device.
   */
  async createPairingCode() {
    const settings = this.getSettings();
    const relayUrl = settings.serverRelayUrl.replace(/\/+$/, "");
    const response = await (0, import_obsidian.requestUrl)({
      url: `${relayUrl}/api/pair/create`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        vaultName: settings.vaultName || "MyVault",
        vaultFolderId: settings.vaultFolderId,
        accessToken: settings.accessToken,
        refreshToken: settings.refreshToken,
        expiryDate: settings.tokenExpiry,
        userEmail: settings.userEmail
      }),
      throwResponseError: false
    });
    if (response.status === 201) {
      return response.json;
    }
    const err = response.json || {};
    throw new Error(err.error || "Failed to generate pairing code");
  }
};

// src/gdrive/gdriveClient.ts
var import_obsidian2 = require("obsidian");
var GDriveClient = class {
  constructor(auth) {
    this.auth = auth;
  }
  /**
   * Executes a direct request to Google Drive API v3 with automatic retry on 401/403 (token expiration)
   * and exponential backoff retry on 429 (rate limits).
   */
  async request(url, options = {}, retryCount = 0) {
    var _a;
    const token = await this.auth.getValidAccessToken();
    const headers = {
      Authorization: `Bearer ${token}`,
      ...options.headers || {}
    };
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url,
        method: options.method || "GET",
        headers,
        body: options.body,
        throwResponseError: false
      });
      if ((response.status === 401 || response.status === 403) && retryCount === 0) {
        const refreshed = await this.auth.refreshAccessToken();
        if (refreshed) {
          return this.request(url, options, retryCount + 1);
        }
      }
      if (response.status === 429 && retryCount < 3) {
        const delay = Math.pow(2, retryCount) * 1e3 + Math.random() * 500;
        await new Promise((resolve) => setTimeout(resolve, delay));
        return this.request(url, options, retryCount + 1);
      }
      if (response.status >= 400) {
        const errorJson = response.json || {};
        const errorMsg = ((_a = errorJson.error) == null ? void 0 : _a.message) || `Google Drive HTTP ${response.status}`;
        throw new Error(errorMsg);
      }
      return response;
    } catch (err) {
      if (retryCount === 0 && (err.message.includes("401") || err.message.includes("403"))) {
        const refreshed = await this.auth.refreshAccessToken();
        if (refreshed) {
          return this.request(url, options, retryCount + 1);
        }
      }
      throw err;
    }
  }
  /**
   * Finds or creates the visible 'ObsidianSync/<vaultName>' folder in the user's Google Drive.
   */
  async ensureVaultRootFolder(vaultName) {
    var _a, _b;
    const sanitizedVaultName = vaultName.trim().replace(/[\/\\:*?"<>|]/g, "_") || "DefaultVault";
    const rootQuery = await this.request(
      `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
        "name = 'ObsidianSync' and mimeType = 'application/vnd.google-apps.folder' and trashed = false and 'root' in parents"
      )}&fields=files(id,name)`
    );
    let rootFolderId;
    if (((_a = rootQuery.json) == null ? void 0 : _a.files) && rootQuery.json.files.length > 0) {
      rootFolderId = rootQuery.json.files[0].id;
    } else {
      rootFolderId = await this.createFolder("ObsidianSync", "root");
    }
    const vaultQuery = await this.request(
      `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
        `name = '${sanitizedVaultName}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false and '${rootFolderId}' in parents`
      )}&fields=files(id,name)`
    );
    let vaultFolderId;
    if (((_b = vaultQuery.json) == null ? void 0 : _b.files) && vaultQuery.json.files.length > 0) {
      vaultFolderId = vaultQuery.json.files[0].id;
    } else {
      vaultFolderId = await this.createFolder(sanitizedVaultName, rootFolderId);
    }
    return { rootFolderId, vaultFolderId };
  }
  /**
   * Fetches metadata for all non-trashed files and folders inside a given parent folder.
   */
  async listFolderChildren(folderId) {
    var _a;
    if (!folderId) return [];
    const q = `'${folderId}' in parents and trashed = false`;
    const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
      q
    )}&fields=files(id,name,mimeType,size,modifiedTime,md5Checksum,parents)&pageSize=1000`;
    const res = await this.request(url);
    return ((_a = res.json) == null ? void 0 : _a.files) || [];
  }
  /**
   * Creates a subfolder in Google Drive.
   */
  async createFolder(name, parentId) {
    const url = "https://www.googleapis.com/drive/v3/files";
    const body = JSON.stringify({
      name,
      mimeType: "application/vnd.google-apps.folder",
      parents: [parentId]
    });
    const res = await this.request(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body
    });
    return res.json.id;
  }
  /**
   * Uploads a new file (including 0-byte empty files) to Google Drive via multipart upload.
   */
  async uploadNewFile(name, parentId, mimeType, data) {
    const metadata = {
      name,
      parents: [parentId],
      mimeType: mimeType || "text/markdown"
    };
    const boundary = "-------314159265358979323846";
    const delimiter = `\r
--${boundary}\r
`;
    const closeDelimiter = `\r
--${boundary}--`;
    const metadataPart = `${delimiter}Content-Type: application/json; charset=UTF-8\r
\r
${JSON.stringify(
      metadata
    )}\r
`;
    const mediaHeader = `${delimiter}Content-Type: ${mimeType || "application/octet-stream"}\r
\r
`;
    const metaBuffer = new TextEncoder().encode(metadataPart);
    const mediaHeaderBuffer = new TextEncoder().encode(mediaHeader);
    const closeBuffer = new TextEncoder().encode(closeDelimiter);
    const combinedLength = metaBuffer.byteLength + mediaHeaderBuffer.byteLength + data.byteLength + closeBuffer.byteLength;
    const combined = new Uint8Array(combinedLength);
    let offset = 0;
    combined.set(metaBuffer, offset);
    offset += metaBuffer.byteLength;
    combined.set(mediaHeaderBuffer, offset);
    offset += mediaHeaderBuffer.byteLength;
    combined.set(new Uint8Array(data), offset);
    offset += data.byteLength;
    combined.set(closeBuffer, offset);
    const url = "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart";
    const res = await this.request(url, {
      method: "POST",
      headers: {
        "Content-Type": `multipart/related; boundary=${boundary}`
      },
      body: combined.buffer
    });
    return res.json;
  }
  /**
   * Updates an existing file's content in Google Drive (media PATCH).
   * Seamlessly handles file modifications and appends.
   */
  async updateFileContent(fileId, mimeType, data) {
    const url = `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=media`;
    const res = await this.request(url, {
      method: "PATCH",
      headers: {
        "Content-Type": mimeType || "application/octet-stream"
      },
      body: data
    });
    return res.json;
  }
  /**
   * Downloads binary file data directly from Google Drive into an ArrayBuffer.
   */
  async downloadFileContent(fileId) {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
    const res = await this.request(url, { method: "GET" });
    return res.arrayBuffer || new ArrayBuffer(0);
  }
  /**
   * Moves a file or folder to Google Drive Trash.
   */
  async trashFile(fileId) {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}`;
    await this.request(url, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ trashed: true })
    });
  }
};

// src/sync/offlineTracker.ts
var import_obsidian3 = require("obsidian");
var OfflineTracker = class {
  constructor(getSettings, saveSettings, onStatusChange) {
    this.getSettings = getSettings;
    this.saveSettings = saveSettings;
    this.onStatusChange = onStatusChange;
    this.isOnline = navigator.onLine;
    this.registerEventListeners();
  }
  registerEventListeners() {
    window.addEventListener("online", () => {
      this.isOnline = true;
      const settings = this.getSettings();
      const count = settings.pendingOfflineChanges.length;
      if (count > 0) {
        new import_obsidian3.Notice(`Google Drive Sync: Back online! ${count} local changes ready to push.`);
      }
      this.onStatusChange("online");
    });
    window.addEventListener("offline", () => {
      this.isOnline = false;
      this.onStatusChange("offline");
      new import_obsidian3.Notice("Google Drive Sync: Offline Mode. Your edits are saved safely on this device.");
    });
  }
  getOnlineState() {
    return this.isOnline;
  }
  async trackFileModification(path) {
    const settings = this.getSettings();
    if (!settings.pendingOfflineChanges.includes(path)) {
      settings.pendingOfflineChanges.push(path);
      await this.saveSettings();
    }
  }
  async clearPendingChanges() {
    const settings = this.getSettings();
    settings.pendingOfflineChanges = [];
    await this.saveSettings();
  }
};

// src/sync/manualSyncEngine.ts
var import_obsidian4 = require("obsidian");

// src/gdrive/folderTree.ts
var FolderTreeManager = class {
  constructor(client, getVaultRootId, setVaultRootId, getVaultName) {
    this.client = client;
    this.getVaultRootId = getVaultRootId;
    this.setVaultRootId = setVaultRootId;
    this.getVaultName = getVaultName;
    // In-memory cache mapping relative folder path (e.g. "Daily/Notes") -> Google Drive Folder ID
    this.folderIdCache = /* @__PURE__ */ new Map();
    // In-flight mutex locks preventing concurrent duplicate folder creation
    this.inFlightFolderCreation = /* @__PURE__ */ new Map();
  }
  clearCache() {
    this.folderIdCache.clear();
    this.inFlightFolderCreation.clear();
  }
  /**
   * Returns a valid root vault folder ID, creating the My Drive/ObsidianSync/<VaultName> folder
   * on Google Drive automatically if not already set.
   */
  async getOrEnsureRootId() {
    let rootId = this.getVaultRootId();
    if (rootId) return rootId;
    const vaultName = this.getVaultName() || "DefaultVault";
    const { vaultFolderId } = await this.client.ensureVaultRootFolder(vaultName);
    await this.setVaultRootId(vaultFolderId);
    return vaultFolderId;
  }
  /**
   * Recursively resolves or creates the Google Drive folder hierarchy for a relative path.
   * Uses in-flight promise deduplication to guarantee zero duplicate folders during parallel file uploads.
   */
  async ensureFolderPath(relativePath) {
    const rootId = await this.getOrEnsureRootId();
    const parts = relativePath.split("/").filter(Boolean);
    parts.pop();
    if (parts.length === 0) {
      return rootId;
    }
    let currentParentId = rootId;
    let currentPath = "";
    for (const segment of parts) {
      currentPath = currentPath ? `${currentPath}/${segment}` : segment;
      if (this.folderIdCache.has(currentPath)) {
        currentParentId = this.folderIdCache.get(currentPath);
        continue;
      }
      if (this.inFlightFolderCreation.has(currentPath)) {
        currentParentId = await this.inFlightFolderCreation.get(currentPath);
        continue;
      }
      const creationPromise = this.resolveOrCreateSegment(segment, currentPath, currentParentId);
      this.inFlightFolderCreation.set(currentPath, creationPromise);
      try {
        currentParentId = await creationPromise;
      } finally {
        this.inFlightFolderCreation.delete(currentPath);
      }
    }
    return currentParentId;
  }
  async resolveOrCreateSegment(segment, currentPath, parentId) {
    const children = await this.client.listFolderChildren(parentId);
    const existingFolder = children.find(
      (c) => c.name === segment && c.mimeType === "application/vnd.google-apps.folder"
    );
    if (existingFolder) {
      this.folderIdCache.set(currentPath, existingFolder.id);
      return existingFolder.id;
    }
    const newFolderId = await this.client.createFolder(segment, parentId);
    this.folderIdCache.set(currentPath, newFolderId);
    return newFolderId;
  }
  /**
   * Recursively scans and indexes all files in the remote vault folder into a flat Map<relativePath, RemoteDriveFile>.
   */
  async scanRemoteVaultTree(rootFolderId) {
    const effectiveRootId = rootFolderId || await this.getOrEnsureRootId();
    const fileMap = /* @__PURE__ */ new Map();
    const traverse = async (folderId, currentPathPrefix) => {
      const items = await this.client.listFolderChildren(folderId);
      for (const item of items) {
        const itemRelativePath = currentPathPrefix ? `${currentPathPrefix}/${item.name}` : item.name;
        if (item.mimeType === "application/vnd.google-apps.folder") {
          this.folderIdCache.set(itemRelativePath, item.id);
          await traverse(item.id, itemRelativePath);
        } else {
          fileMap.set(itemRelativePath, item);
        }
      }
    };
    await traverse(effectiveRootId, "");
    return fileMap;
  }
};

// src/sync/localHasher.ts
var DEFAULT_IGNORED_PATTERNS = [
  "^.git($|/)",
  "^node_modules($|/)",
  "^.trash($|/)",
  "^.obsidian/workspace",
  "^.obsidian/cache",
  "^.DS_Store$",
  "^Thumbs.db$",
  "~$",
  ".tmp$"
];
var LocalHasher = class {
  constructor(vault, getCustomPatterns) {
    this.vault = vault;
    this.getCustomPatterns = getCustomPatterns;
  }
  /**
   * Computes SHA-256 hex string for binary buffer using Web Crypto API.
   */
  async computeHash(buffer) {
    const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  isIgnored(path) {
    const custom = this.getCustomPatterns();
    const all = [...DEFAULT_IGNORED_PATTERNS, ...custom];
    for (const pat of all) {
      try {
        const reg = new RegExp(pat, "i");
        if (reg.test(path)) return true;
      } catch (e) {
      }
    }
    return false;
  }
  /**
   * Scans all non-ignored vault files and computes their hashes in parallel chunks.
   * Seamlessly handles empty 0-byte notes.
   */
  async scanVault() {
    const files = this.vault.getFiles();
    const valid = files.filter((f) => !this.isIgnored(f.path));
    const result = [];
    const BATCH_SIZE = 50;
    for (let i = 0; i < valid.length; i += BATCH_SIZE) {
      const batch = valid.slice(i, i + BATCH_SIZE);
      const batchEntries = await Promise.all(
        batch.map(async (file) => {
          try {
            const data = await this.vault.readBinary(file);
            const hash = await this.computeHash(data);
            return {
              relativePath: file.path,
              hash,
              size: file.stat.size,
              mtime: file.stat.mtime
            };
          } catch (e) {
            return null;
          }
        })
      );
      for (const entry of batchEntries) {
        if (entry) result.push(entry);
      }
    }
    return result;
  }
};

// src/sync/manualSyncEngine.ts
var ManualSyncEngine = class {
  constructor(app, getSettings, loadSettings, saveSettings, client, offlineTracker, statusBar) {
    this.app = app;
    this.getSettings = getSettings;
    this.loadSettings = loadSettings;
    this.saveSettings = saveSettings;
    this.client = client;
    this.offlineTracker = offlineTracker;
    this.statusBar = statusBar;
    this.hasher = new LocalHasher(app.vault, () => this.getSettings().customIgnoredPatterns);
    this.folderTree = new FolderTreeManager(
      client,
      () => this.getSettings().vaultFolderId,
      async (id) => {
        const settings = this.getSettings();
        settings.vaultFolderId = id;
        await this.saveSettings();
      },
      () => this.getSettings().vaultName
    );
  }
  /**
   * PUSH: High-Speed Parallel Upload of local vault changes directly to Google Drive.
   * Modifies existing files in-place with zero duplicate creations.
   */
  async push() {
    await this.loadSettings();
    const settings = this.getSettings();
    settings.syncedFileHashes = settings.syncedFileHashes || {};
    if (!settings.accessToken) {
      new import_obsidian4.Notice("Google Drive Sync: Please log in or pair device in plugin settings.");
      this.statusBar.setStatus("unauthenticated");
      return;
    }
    if (!navigator.onLine) {
      new import_obsidian4.Notice("Google Drive Sync: You are offline. Changes remain saved locally.");
      this.statusBar.setStatus("offline", `${settings.pendingOfflineChanges.length} pending`);
      return;
    }
    this.statusBar.setStatus("syncing", "Scanning...");
    new import_obsidian4.Notice("Google Drive Sync: Checking vault changes...");
    try {
      const rootFolderId = await this.folderTree.getOrEnsureRootId();
      const [localFiles, remoteMap] = await Promise.all([
        this.hasher.scanVault(),
        this.folderTree.scanRemoteVaultTree(rootFolderId)
      ]);
      const toUpload = [];
      for (const local of localFiles) {
        const cleanPath = local.relativePath.replace(/\\/g, "/").replace(/^\/+/, "");
        const remote = remoteMap.get(cleanPath);
        if (!remote) {
          toUpload.push({ local });
        } else {
          const remoteSize = remote.size !== void 0 ? parseInt(remote.size, 10) : 0;
          const cachedHash = settings.syncedFileHashes[cleanPath];
          if (cachedHash && cachedHash === local.hash && remoteSize === local.size) {
            continue;
          }
          if (remoteSize === local.size && !cachedHash) {
            const remoteTime = remote.modifiedTime ? new Date(remote.modifiedTime).getTime() : 0;
            if (local.mtime <= remoteTime + 1e3) {
              settings.syncedFileHashes[cleanPath] = local.hash;
              continue;
            }
          }
          toUpload.push({ local, remote });
        }
      }
      if (toUpload.length === 0) {
        new import_obsidian4.Notice("Google Drive Sync: Everything is up to date. Nothing to push.");
        settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
        settings.lastSyncStatus = "up-to-date";
        await this.saveSettings();
        await this.offlineTracker.clearPendingChanges();
        this.statusBar.setStatus("up-to-date");
        return;
      }
      const uniqueFolders = Array.from(
        new Set(
          toUpload.map((item) => {
            const parts = item.local.relativePath.replace(/\\/g, "/").split("/").filter(Boolean);
            parts.pop();
            return parts.join("/");
          })
        )
      ).filter(Boolean);
      if (uniqueFolders.length > 0) {
        this.statusBar.setStatus("syncing", "Preparing folders...");
        await Promise.all(uniqueFolders.map((p) => this.folderTree.ensureFolderPath(`${p}/placeholder.md`)));
      }
      let uploadedCount = 0;
      const total = toUpload.length;
      const CONCURRENCY_BATCH = 10;
      for (let i = 0; i < total; i += CONCURRENCY_BATCH) {
        const batch = toUpload.slice(i, i + CONCURRENCY_BATCH);
        await Promise.all(
          batch.map(async (item) => {
            const cleanPath = item.local.relativePath.replace(/\\/g, "/").replace(/^\/+/, "");
            const abstractFile = this.app.vault.getAbstractFileByPath(item.local.relativePath);
            if (abstractFile instanceof import_obsidian4.TFile) {
              const binaryData = await this.app.vault.readBinary(abstractFile);
              const mimeType = this.getMimeType(cleanPath);
              if (item.remote) {
                await this.client.updateFileContent(item.remote.id, mimeType, binaryData);
              } else {
                const parentFolderId = await this.folderTree.ensureFolderPath(cleanPath);
                const filename = cleanPath.split("/").pop();
                await this.client.uploadNewFile(filename, parentFolderId, mimeType, binaryData);
              }
              settings.syncedFileHashes[cleanPath] = item.local.hash;
              uploadedCount++;
              this.statusBar.setStatus("syncing", `${uploadedCount}/${total}`);
            }
          })
        );
      }
      settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
      settings.lastSyncStatus = "up-to-date";
      await this.saveSettings();
      await this.offlineTracker.clearPendingChanges();
      this.statusBar.setStatus("up-to-date");
      new import_obsidian4.Notice(`Google Drive Sync: Successfully pushed ${uploadedCount} file(s) to Drive!`);
    } catch (err) {
      console.error("Push Error:", err);
      settings.lastSyncStatus = "failed";
      await this.saveSettings();
      this.statusBar.setStatus("failed");
      new import_obsidian4.Notice(`Google Drive Push failed: ${err.message}`);
    }
  }
  /**
   * PULL: Downloads cloud vault changes directly from Google Drive.
   */
  async pull() {
    await this.loadSettings();
    const settings = this.getSettings();
    settings.syncedFileHashes = settings.syncedFileHashes || {};
    if (!settings.accessToken) {
      new import_obsidian4.Notice("Google Drive Sync: Please log in or pair device in plugin settings.");
      this.statusBar.setStatus("unauthenticated");
      return;
    }
    if (!navigator.onLine) {
      new import_obsidian4.Notice("Google Drive Sync: You are offline.");
      this.statusBar.setStatus("offline");
      return;
    }
    this.statusBar.setStatus("syncing", "Scanning cloud...");
    new import_obsidian4.Notice("Google Drive Sync: Checking Google Drive for changes...");
    try {
      const rootFolderId = await this.folderTree.getOrEnsureRootId();
      const [localFiles, remoteMap] = await Promise.all([
        this.hasher.scanVault(),
        this.folderTree.scanRemoteVaultTree(rootFolderId)
      ]);
      const localMap = /* @__PURE__ */ new Map();
      for (const lf of localFiles) {
        localMap.set(lf.relativePath.replace(/\\/g, "/").replace(/^\/+/, ""), lf);
      }
      const toDownload = [];
      for (const [remotePath, remoteFile] of remoteMap.entries()) {
        const local = localMap.get(remotePath);
        const remoteSize = remoteFile.size !== void 0 ? parseInt(remoteFile.size, 10) : 0;
        const cachedHash = settings.syncedFileHashes[remotePath];
        if (!local) {
          toDownload.push(remoteFile);
        } else if (remoteSize !== local.size) {
          toDownload.push(remoteFile);
        }
      }
      if (toDownload.length === 0) {
        new import_obsidian4.Notice("Google Drive Sync: Your vault is already up to date with Google Drive.");
        settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
        settings.lastSyncStatus = "up-to-date";
        await this.saveSettings();
        this.statusBar.setStatus("up-to-date");
        return;
      }
      let downloadedCount = 0;
      const total = toDownload.length;
      for (const remoteFile of toDownload) {
        const relPath = this.getRelativePathForRemote(remoteFile, remoteMap);
        const data = await this.client.downloadFileContent(remoteFile.id);
        await this.ensureLocalParentDir(relPath);
        const existing = this.app.vault.getAbstractFileByPath(relPath);
        if (existing instanceof import_obsidian4.TFile) {
          await this.app.vault.modifyBinary(existing, data);
        } else {
          await this.app.vault.createBinary(relPath, data);
        }
        const newHash = await this.hasher.computeHash(data);
        settings.syncedFileHashes[relPath] = newHash;
        downloadedCount++;
        this.statusBar.setStatus("syncing", `Pulling ${downloadedCount}/${total}`);
      }
      settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
      settings.lastSyncStatus = "up-to-date";
      await this.saveSettings();
      this.statusBar.setStatus("up-to-date");
      new import_obsidian4.Notice(`Google Drive Sync: Successfully downloaded ${downloadedCount} note(s)!`);
    } catch (err) {
      console.error("Pull Error:", err);
      settings.lastSyncStatus = "failed";
      await this.saveSettings();
      this.statusBar.setStatus("failed");
      new import_obsidian4.Notice(`Google Drive Pull failed: ${err.message}`);
    }
  }
  getRelativePathForRemote(targetFile, remoteMap) {
    for (const [path, file] of remoteMap.entries()) {
      if (file.id === targetFile.id) return path;
    }
    return targetFile.name;
  }
  async ensureLocalParentDir(relativePath) {
    const parts = relativePath.replace(/\\/g, "/").split("/").filter(Boolean);
    parts.pop();
    if (parts.length === 0) return;
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const exists = this.app.vault.getAbstractFileByPath(current);
      if (!exists) {
        try {
          await this.app.vault.createFolder(current);
        } catch (e) {
        }
      }
    }
  }
  getMimeType(path) {
    if (path.endsWith(".md")) return "text/markdown; charset=UTF-8";
    if (path.endsWith(".png")) return "image/png";
    if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
    if (path.endsWith(".pdf")) return "application/pdf";
    if (path.endsWith(".json") || path.endsWith(".canvas")) return "application/json";
    return "application/octet-stream";
  }
};

// src/ui/statusBar.ts
var StatusBarController = class {
  constructor(statusBarEl) {
    this.statusBarEl = statusBarEl;
  }
  setStatus(state, extraInfo) {
    let icon = "\u2601\uFE0F";
    let text = "Drive";
    switch (state) {
      case "up-to-date":
        icon = "\u{1F7E2}";
        text = "Drive: Up to date";
        break;
      case "local-changes":
        icon = "\u{1F535}";
        text = "Drive: Local Changes";
        break;
      case "cloud-newer":
        icon = "\u{1F7E1}";
        text = "Drive: Cloud Newer";
        break;
      case "syncing":
        icon = "\u23F3";
        text = extraInfo ? `Drive: ${extraInfo}` : "Drive: Syncing...";
        break;
      case "offline":
        icon = "\u{1F4E1}";
        text = extraInfo ? `Drive: Offline (${extraInfo})` : "Drive: Offline";
        break;
      case "failed":
        icon = "\u{1F534}";
        text = "Drive: Sync Failed";
        break;
      case "unauthenticated":
        icon = "\u26AA";
        text = "Drive: Not Connected";
        break;
    }
    this.statusBarEl.setText(`${icon} ${text}`);
    this.statusBarEl.setAttribute("title", `Obsidian Google Drive Sync: ${text}`);
  }
};

// src/ui/settingsTab.ts
var import_obsidian5 = require("obsidian");
var GoogleDriveSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.pairingCodeInput = "";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Google Drive Sync Settings" });
    containerEl.createEl("p", {
      text: "Direct manual cloud synchronization for your vault using your personal Google Drive account. Zero third-party database storage.",
      cls: "setting-item-description"
    });
    new import_obsidian5.Setting(containerEl).setName("Google Drive Status").setDesc(
      this.plugin.settings.accessToken ? `Connected as ${this.plugin.settings.userEmail || "Google User"} (Vault: My Drive/ObsidianSync/${this.plugin.settings.vaultName})` : "Not connected to Google Drive"
    ).addButton((btn) => {
      if (this.plugin.settings.accessToken) {
        btn.setButtonText("Disconnect").setWarning().onClick(async () => {
          this.plugin.settings.accessToken = "";
          this.plugin.settings.refreshToken = "";
          this.plugin.settings.userEmail = "";
          this.plugin.settings.vaultFolderId = "";
          this.plugin.settings.lastSyncStatus = "unauthenticated";
          await this.plugin.saveSettings();
          new import_obsidian5.Notice("Disconnected Google Drive");
          this.display();
        });
      } else {
        btn.setButtonText("Open Web Setup Wizard").setCta().onClick(() => {
          window.open(this.plugin.settings.serverRelayUrl || "http://localhost:5173", "_blank");
        });
      }
    });
    containerEl.createEl("h3", { text: "Device Pairing (Mobile \u2194 Desktop)" });
    new import_obsidian5.Setting(containerEl).setName("Enter 6-Digit Pair Code").setDesc("Enter a code generated from your other device or web setup portal.").addText(
      (text) => text.setPlaceholder("e.g. SYNC-849").setValue(this.pairingCodeInput).onChange((val) => this.pairingCodeInput = val)
    ).addButton(
      (btn) => btn.setButtonText("Link Device").setCta().onClick(async () => {
        if (!this.pairingCodeInput.trim()) {
          new import_obsidian5.Notice("Please enter a 6-digit pairing code");
          return;
        }
        try {
          btn.setDisabled(true);
          await this.plugin.auth.redeemPairingCode(this.pairingCodeInput);
          new import_obsidian5.Notice("Device paired successfully with Google Drive!");
          this.display();
        } catch (err) {
          new import_obsidian5.Notice(`Pairing failed: ${err.message}`);
        } finally {
          btn.setDisabled(false);
        }
      })
    );
    if (this.plugin.settings.accessToken) {
      new import_obsidian5.Setting(containerEl).setName("Generate Pairing Code for Another Device").setDesc("Creates a temporary 10-minute 6-digit code you can enter on your other device.").addButton(
        (btn) => btn.setButtonText("Generate Code").onClick(async () => {
          try {
            btn.setDisabled(true);
            const result = await this.plugin.auth.createPairingCode();
            new import_obsidian5.Notice(`Pairing Code: ${result.code} (Expires in 10 mins)`, 1e4);
          } catch (err) {
            new import_obsidian5.Notice(`Failed to generate code: ${err.message}`);
          } finally {
            btn.setDisabled(false);
          }
        })
      );
    }
    containerEl.createEl("h3", { text: "Vault Configuration" });
    new import_obsidian5.Setting(containerEl).setName("Vault Name").setDesc("The subfolder name in Google Drive (My Drive/ObsidianSync/<VaultName>)").addText(
      (text) => text.setPlaceholder("MyVault").setValue(this.plugin.settings.vaultName).onChange(async (value) => {
        this.plugin.settings.vaultName = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Pairing Relay / Server URL").setDesc("Lightweight relay server URL for 1-time OAuth callback & pairing handshake.").addText(
      (text) => text.setPlaceholder("http://localhost:5050").setValue(this.plugin.settings.serverRelayUrl).onChange(async (value) => {
        this.plugin.settings.serverRelayUrl = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Sync Ignore Rules" });
    new import_obsidian5.Setting(containerEl).setName("Custom Ignored Regex Patterns").setDesc("Enter one regex pattern per line (e.g. ^Private/ or \\.secret$)").addTextArea(
      (text) => text.setPlaceholder("^Private/\n\\.secret$").setValue(this.plugin.settings.customIgnoredPatterns.join("\n")).onChange(async (value) => {
        this.plugin.settings.customIgnoredPatterns = value.split("\n").map((s) => s.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var GoogleDriveSyncPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    const statusBarEl = this.addStatusBarItem();
    this.statusBar = new StatusBarController(statusBarEl);
    this.statusBar.setStatus(this.settings.lastSyncStatus);
    this.auth = new GDriveAuth(
      () => this.settings,
      () => this.saveSettings()
    );
    this.client = new GDriveClient(this.auth);
    this.offlineTracker = new OfflineTracker(
      () => this.settings,
      () => this.saveSettings(),
      (status) => {
        if (status === "offline") {
          this.statusBar.setStatus("offline", `${this.settings.pendingOfflineChanges.length} pending`);
        } else {
          this.statusBar.setStatus(this.settings.lastSyncStatus);
        }
      }
    );
    this.syncEngine = new ManualSyncEngine(
      this.app,
      () => this.settings,
      () => this.loadSettings(),
      () => this.saveSettings(),
      this.client,
      this.offlineTracker,
      this.statusBar
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!navigator.onLine) {
          this.offlineTracker.trackFileModification(file.path);
          this.statusBar.setStatus("offline", `${this.settings.pendingOfflineChanges.length} pending`);
        } else if (this.settings.lastSyncStatus === "up-to-date") {
          this.settings.lastSyncStatus = "local-changes";
          this.statusBar.setStatus("local-changes");
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!navigator.onLine) {
          this.offlineTracker.trackFileModification(file.path);
        } else if (this.settings.lastSyncStatus === "up-to-date") {
          this.settings.lastSyncStatus = "local-changes";
          this.statusBar.setStatus("local-changes");
        }
      })
    );
    this.addRibbonIcon("upload-cloud", "Push to Google Drive", async () => {
      await this.syncEngine.push();
    });
    this.addRibbonIcon("download-cloud", "Pull from Google Drive", async () => {
      await this.syncEngine.pull();
    });
    this.addCommand({
      id: "gdrive-push",
      name: "Push vault to Google Drive",
      callback: async () => {
        await this.syncEngine.push();
      }
    });
    this.addCommand({
      id: "gdrive-pull",
      name: "Pull vault from Google Drive",
      callback: async () => {
        await this.syncEngine.pull();
      }
    });
    this.addSettingTab(new GoogleDriveSettingTab(this.app, this));
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
