/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GoogleDriveSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  serverRelayUrl: "https://obsidian-gdrive-backend.onrender.com",
  accessToken: "",
  refreshToken: "",
  tokenExpiry: 0,
  userEmail: "",
  vaultName: "DefaultVault",
  vaultFolderId: "",
  deviceId: `device_${Math.random().toString(36).substring(2, 9)}`,
  lastSyncTime: null,
  lastSyncStatus: "unauthenticated",
  customIgnoredPatterns: [],
  pendingOfflineChanges: [],
  pendingDeletedPaths: [],
  syncedFileHashes: {},
  syncConfigDir: true,
  syncCoreSettings: true,
  syncAppearance: true,
  syncCommunityPlugins: true,
  syncWorkspaceLayout: false
};

// src/gdrive/gdriveAuth.ts
var import_obsidian = require("obsidian");
var GDriveAuth = class {
  constructor(getSettings, saveSettings) {
    this.getSettings = getSettings;
    this.saveSettings = saveSettings;
  }
  /**
   * Returns a valid access token. If token is near expiration (within 5 minutes) or expired,
   * automatically triggers a proactive refresh before returning.
   */
  async getValidAccessToken() {
    const settings = this.getSettings();
    if (!settings.accessToken) {
      throw new Error("Google Drive is not authenticated. Please log in or enter a pairing code in plugin settings.");
    }
    const now = Date.now();
    const isExpiringSoon = settings.tokenExpiry && now >= settings.tokenExpiry - 5 * 60 * 1e3;
    if (isExpiringSoon && settings.refreshToken) {
      await this.refreshAccessToken();
    }
    return this.getSettings().accessToken;
  }
  /**
   * Refreshes the Google OAuth access token using the stored refresh_token.
   */
  async refreshAccessToken() {
    var _a, _b, _c, _d;
    const settings = this.getSettings();
    if (!settings.refreshToken) return false;
    const cloudRelay = "https://obsidian-gdrive-backend.onrender.com";
    const urlsToTry = [];
    if (settings.serverRelayUrl) {
      urlsToTry.push(settings.serverRelayUrl.replace(/\/+$/, ""));
    }
    if (!urlsToTry.includes(cloudRelay)) {
      urlsToTry.push(cloudRelay);
    }
    if (((_a = settings.serverRelayUrl) == null ? void 0 : _a.includes("localhost")) || ((_b = settings.serverRelayUrl) == null ? void 0 : _b.includes("127.0.0.1"))) {
      urlsToTry.sort((a, b) => a === cloudRelay ? -1 : 1);
    }
    for (const relayUrl of urlsToTry) {
      try {
        const response = await (0, import_obsidian.requestUrl)({
          url: `${relayUrl}/api/auth/google/refresh`,
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ refreshToken: settings.refreshToken }),
          throw: false
        });
        if (response.status === 200 && ((_c = response.json) == null ? void 0 : _c.accessToken)) {
          const data = response.json;
          settings.accessToken = data.accessToken;
          if (data.expiryDate) {
            settings.tokenExpiry = data.expiryDate;
          } else {
            settings.tokenExpiry = Date.now() + 3600 * 1e3;
          }
          if (((_d = settings.serverRelayUrl) == null ? void 0 : _d.includes("localhost")) && relayUrl === cloudRelay) {
            settings.serverRelayUrl = cloudRelay;
          }
          await this.saveSettings();
          return true;
        }
      } catch (err) {
        console.warn(`Failed to refresh Google OAuth token via ${relayUrl}:`, err);
      }
    }
    return false;
  }
  /**
   * Redeems a 6-digit pairing code to link this device.
   */
  async redeemPairingCode(code) {
    var _a, _b, _c, _d;
    const settings = this.getSettings();
    const cloudRelay = "https://obsidian-gdrive-backend.onrender.com";
    const urlsToTry = [];
    if (settings.serverRelayUrl) {
      urlsToTry.push(settings.serverRelayUrl.replace(/\/+$/, ""));
    }
    if (!urlsToTry.includes(cloudRelay)) {
      urlsToTry.push(cloudRelay);
    }
    if (((_a = settings.serverRelayUrl) == null ? void 0 : _a.includes("localhost")) || ((_b = settings.serverRelayUrl) == null ? void 0 : _b.includes("127.0.0.1"))) {
      urlsToTry.sort((a, b) => a === cloudRelay ? -1 : 1);
    }
    let lastError = "Pairing failed";
    for (const relayUrl of urlsToTry) {
      try {
        const response = await (0, import_obsidian.requestUrl)({
          url: `${relayUrl}/api/pair/${encodeURIComponent(code.trim())}`,
          method: "GET",
          headers: { "Content-Type": "application/json" },
          throw: false
        });
        if (response.status === 200 && ((_c = response.json) == null ? void 0 : _c.accessToken)) {
          const data = response.json;
          settings.accessToken = data.accessToken;
          if (data.refreshToken) settings.refreshToken = data.refreshToken;
          if (data.expiryDate) settings.tokenExpiry = data.expiryDate;
          if (data.userEmail) settings.userEmail = data.userEmail;
          if (data.vaultName) settings.vaultName = data.vaultName;
          if (data.vaultFolderId) settings.vaultFolderId = data.vaultFolderId;
          settings.serverRelayUrl = relayUrl;
          settings.lastSyncStatus = "up-to-date";
          await this.saveSettings();
          return true;
        } else if (response.status !== 404) {
          lastError = ((_d = response.json) == null ? void 0 : _d.error) || `Pairing failed (HTTP ${response.status})`;
        }
      } catch (err) {
        lastError = err.message || "Connection error";
      }
    }
    throw new Error(lastError);
  }
  /**
   * Generates a 6-digit pairing code on this device to share with another device.
   */
  async createPairingCode() {
    const settings = this.getSettings();
    const relayUrl = settings.serverRelayUrl.replace(/\/+$/, "");
    const response = await (0, import_obsidian.requestUrl)({
      url: `${relayUrl}/api/pair/create`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        vaultName: settings.vaultName || "MyVault",
        vaultFolderId: settings.vaultFolderId,
        accessToken: settings.accessToken,
        refreshToken: settings.refreshToken,
        expiryDate: settings.tokenExpiry,
        userEmail: settings.userEmail
      }),
      throw: false
    });
    if (response.status === 201) {
      return response.json;
    }
    const err = response.json || {};
    throw new Error(err.error || "Failed to generate pairing code");
  }
};

// src/gdrive/gdriveClient.ts
var import_obsidian2 = require("obsidian");
function escapeDriveQuery(str) {
  return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}
var RESUMABLE_UPLOAD_THRESHOLD = 5 * 1024 * 1024;
var CHUNK_SIZE = 2 * 1024 * 1024;
var GDriveClient = class {
  constructor(auth) {
    this.auth = auth;
  }
  /**
   * Executes a direct request to Google Drive API v3 with automatic retry on 401/403 (token expiration)
   * and exponential backoff retry on 429 (rate limits).
   */
  async request(url, options = {}, retryCount = 0) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    const token = await this.auth.getValidAccessToken();
    const headers = {
      Authorization: `Bearer ${token}`,
      ...options.headers || {}
    };
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url,
        method: options.method || "GET",
        headers,
        body: options.body,
        throw: false
      });
      if ((response.status === 401 || response.status === 403) && retryCount === 0) {
        const refreshed = await this.auth.refreshAccessToken();
        if (refreshed) {
          return this.request(url, options, retryCount + 1);
        }
      }
      if ((response.status === 429 || response.status === 503) && retryCount < 3) {
        const delay = Math.pow(2, retryCount) * 1e3 + Math.random() * 500;
        await new Promise((resolve) => setTimeout(resolve, delay));
        return this.request(url, options, retryCount + 1);
      }
      if (response.status >= 400) {
        const errorJson = response.json || {};
        const errorMsg = ((_a = errorJson.error) == null ? void 0 : _a.message) || `Google Drive HTTP ${response.status}`;
        throw new Error(errorMsg);
      }
      return response;
    } catch (err) {
      if (retryCount === 0 && (((_b = err.message) == null ? void 0 : _b.includes("401")) || ((_c = err.message) == null ? void 0 : _c.includes("403")))) {
        const refreshed = await this.auth.refreshAccessToken();
        if (refreshed) {
          return this.request(url, options, retryCount + 1);
        }
      }
      const isNetworkError = ((_d = err.message) == null ? void 0 : _d.includes("UnknownHostException")) || ((_e = err.message) == null ? void 0 : _e.includes("ENOTFOUND")) || ((_f = err.message) == null ? void 0 : _f.includes("ECONNRESET")) || ((_g = err.message) == null ? void 0 : _g.includes("ETIMEDOUT")) || ((_h = err.message) == null ? void 0 : _h.includes("Failed to fetch")) || ((_i = err.message) == null ? void 0 : _i.includes("Network Error"));
      if (isNetworkError && retryCount < 2) {
        const delay = (retryCount + 1) * 1500;
        await new Promise((resolve) => setTimeout(resolve, delay));
        return this.request(url, options, retryCount + 1);
      }
      if (isNetworkError) {
        throw new Error("NETWORK_OFFLINE: Unable to reach Google Drive (DNS / network offline). Please check your internet connection.");
      }
      throw err;
    }
  }
  /**
   * Finds or creates the visible 'VaultGlide/<vaultName>' folder in the user's Google Drive.
   * Prevents duplicate root folders across reconnects.
   */
  async ensureVaultRootFolder(vaultName) {
    var _a, _b;
    const sanitizedVaultName = vaultName.trim().replace(/[\/\\:*?"<>|]/g, "_") || "DefaultVault";
    const escapedVaultName = escapeDriveQuery(sanitizedVaultName);
    const rootQuery = await this.request(
      `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
        "(name = 'VaultGlide' or name = 'ObsidianSync') and mimeType = 'application/vnd.google-apps.folder' and trashed = false"
      )}&fields=files(id,name,createdTime)&orderBy=createdTime asc`
    );
    let rootFolderId;
    if (((_a = rootQuery.json) == null ? void 0 : _a.files) && rootQuery.json.files.length > 0) {
      const primaryFolder = rootQuery.json.files.find((f) => f.name === "VaultGlide");
      rootFolderId = (primaryFolder == null ? void 0 : primaryFolder.id) || rootQuery.json.files[0].id;
    } else {
      rootFolderId = await this.createFolder("VaultGlide", "root");
    }
    const vaultQuery = await this.request(
      `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
        `name = '${escapedVaultName}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false and '${rootFolderId}' in parents`
      )}&fields=files(id,name,createdTime)&orderBy=createdTime asc`
    );
    let vaultFolderId;
    if (((_b = vaultQuery.json) == null ? void 0 : _b.files) && vaultQuery.json.files.length > 0) {
      vaultFolderId = vaultQuery.json.files[0].id;
    } else {
      vaultFolderId = await this.createFolder(sanitizedVaultName, rootFolderId);
    }
    return { rootFolderId, vaultFolderId };
  }
  /**
   * Fetches metadata for all non-trashed files and folders inside a given parent folder.
   */
  async listFolderChildren(folderId) {
    var _a;
    if (!folderId) return [];
    const q = `'${folderId}' in parents and trashed = false`;
    const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(
      q
    )}&fields=files(id,name,mimeType,size,modifiedTime,md5Checksum,parents)&pageSize=1000`;
    const res = await this.request(url);
    return ((_a = res.json) == null ? void 0 : _a.files) || [];
  }
  /**
   * Creates a subfolder in Google Drive.
   */
  async createFolder(name, parentId) {
    const url = "https://www.googleapis.com/drive/v3/files";
    const body = JSON.stringify({
      name,
      mimeType: "application/vnd.google-apps.folder",
      parents: [parentId]
    });
    const res = await this.request(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body
    });
    return res.json.id;
  }
  /**
   * Uploads a new file (including 0-byte empty files and large media/videos) to Google Drive.
   * - Files <= 5 MB: Fast multipart upload.
   * - Files > 5 MB: Resumable chunked upload (prevents mobile OOM & handles network interruption).
   */
  async uploadNewFile(name, parentId, mimeType, data, onProgress) {
    const dataBytes = data instanceof Uint8Array ? data : new Uint8Array(data);
    if (dataBytes.byteLength > RESUMABLE_UPLOAD_THRESHOLD) {
      return this.uploadResumable(name, parentId, mimeType, dataBytes, false, onProgress);
    }
    return this.uploadMultipart(name, parentId, mimeType, dataBytes);
  }
  /**
   * Updates an existing file's content in Google Drive.
   * - Files <= 5 MB: Direct media PATCH.
   * - Files > 5 MB: Resumable chunked upload.
   */
  async updateFileContent(fileId, mimeType, data, onProgress) {
    const dataBytes = data instanceof Uint8Array ? data : new Uint8Array(data);
    if (dataBytes.byteLength > RESUMABLE_UPLOAD_THRESHOLD) {
      return this.uploadResumable("", fileId, mimeType, dataBytes, true, onProgress);
    }
    return this.updateMediaDirect(fileId, mimeType, dataBytes);
  }
  /**
   * Fast Multipart upload for files <= 5 MB.
   */
  async uploadMultipart(name, parentId, mimeType, data) {
    const metadata = {
      name,
      parents: [parentId],
      mimeType: mimeType || "text/markdown"
    };
    const boundary = "-------314159265358979323846";
    const delimiter = `\r
--${boundary}\r
`;
    const closeDelimiter = `\r
--${boundary}--`;
    const metadataPart = `${delimiter}Content-Type: application/json; charset=UTF-8\r
\r
${JSON.stringify(
      metadata
    )}\r
`;
    const mediaHeader = `${delimiter}Content-Type: ${mimeType || "application/octet-stream"}\r
\r
`;
    const metaBuffer = new TextEncoder().encode(metadataPart);
    const mediaHeaderBuffer = new TextEncoder().encode(mediaHeader);
    const closeBuffer = new TextEncoder().encode(closeDelimiter);
    const combinedLength = metaBuffer.byteLength + mediaHeaderBuffer.byteLength + data.byteLength + closeBuffer.byteLength;
    const combined = new Uint8Array(combinedLength);
    let offset = 0;
    combined.set(metaBuffer, offset);
    offset += metaBuffer.byteLength;
    combined.set(mediaHeaderBuffer, offset);
    offset += mediaHeaderBuffer.byteLength;
    combined.set(data, offset);
    offset += data.byteLength;
    combined.set(closeBuffer, offset);
    const url = "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart";
    const res = await this.request(url, {
      method: "POST",
      headers: {
        "Content-Type": `multipart/related; boundary=${boundary}`
      },
      body: combined.buffer.slice(combined.byteOffset, combined.byteOffset + combined.byteLength)
    });
    return res.json;
  }
  /**
   * Direct Media PATCH for files <= 5 MB.
   */
  async updateMediaDirect(fileId, mimeType, data) {
    const url = `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=media`;
    const res = await this.request(url, {
      method: "PATCH",
      headers: {
        "Content-Type": mimeType || "application/octet-stream"
      },
      body: data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength)
    });
    return res.json;
  }
  /**
   * Resumable Chunked Upload Protocol for large files & video:
   * 1. Initiates resumable session with Google Drive.
   * 2. Streams the file in 2 MB chunks (multiples of 256 KB).
   * 3. Queries status and resumes upload seamlessly if any chunk drops.
   */
  async uploadResumable(name, targetId, mimeType, data, isUpdate, onProgress) {
    const token = await this.auth.getValidAccessToken();
    const totalBytes = data.byteLength;
    const finalMime = mimeType || "application/octet-stream";
    const initUrl = isUpdate ? `https://www.googleapis.com/upload/drive/v3/files/${targetId}?uploadType=resumable` : "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable";
    const metadata = isUpdate ? {} : {
      name,
      parents: [targetId],
      mimeType: finalMime
    };
    const initRes = await (0, import_obsidian2.requestUrl)({
      url: initUrl,
      method: isUpdate ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": finalMime,
        "X-Upload-Content-Length": totalBytes.toString()
      },
      body: JSON.stringify(metadata),
      throw: false
    });
    if (initRes.status >= 400) {
      throw new Error(`Failed to initiate resumable upload session (HTTP ${initRes.status}): ${initRes.text || ""}`);
    }
    const sessionUri = initRes.headers["location"] || initRes.headers["Location"];
    if (!sessionUri) {
      throw new Error("Google Drive did not return a resumable session URI.");
    }
    let start = 0;
    let lastResult = null;
    while (start < totalBytes) {
      const end = Math.min(start + CHUNK_SIZE - 1, totalBytes - 1);
      const chunkLength = end - start + 1;
      const chunkBytes = data.slice(start, end + 1);
      const chunkBuffer = chunkBytes.buffer.slice(chunkBytes.byteOffset, chunkBytes.byteOffset + chunkBytes.byteLength);
      let chunkSuccess = false;
      let retryCount = 0;
      while (!chunkSuccess && retryCount < 4) {
        try {
          const chunkRes = await (0, import_obsidian2.requestUrl)({
            url: sessionUri,
            method: "PUT",
            headers: {
              "Content-Range": `bytes ${start}-${end}/${totalBytes}`,
              "Content-Length": chunkLength.toString()
            },
            body: chunkBuffer,
            throw: false
          });
          if (chunkRes.status === 308) {
            chunkSuccess = true;
            start = end + 1;
            if (onProgress) onProgress(start, totalBytes);
          } else if (chunkRes.status === 200 || chunkRes.status === 201) {
            chunkSuccess = true;
            lastResult = chunkRes.json;
            start = totalBytes;
            if (onProgress) onProgress(totalBytes, totalBytes);
          } else if (chunkRes.status >= 500 || chunkRes.status === 429) {
            retryCount++;
            const delay = Math.pow(2, retryCount) * 1e3 + Math.random() * 500;
            await new Promise((r) => setTimeout(r, delay));
            const resumedStart = await this.queryResumableStatus(sessionUri, totalBytes);
            if (resumedStart !== null) {
              start = resumedStart;
              break;
            }
          } else {
            throw new Error(`Resumable chunk upload failed (HTTP ${chunkRes.status}): ${chunkRes.text || ""}`);
          }
        } catch (err) {
          retryCount++;
          if (retryCount >= 4) throw err;
          const delay = Math.pow(2, retryCount) * 1500;
          await new Promise((r) => setTimeout(r, delay));
          const resumedStart = await this.queryResumableStatus(sessionUri, totalBytes);
          if (resumedStart !== null) {
            start = resumedStart;
            break;
          }
        }
      }
      if (!chunkSuccess && start < totalBytes) {
        throw new Error(`Failed to upload chunk starting at byte ${start} after multiple retries.`);
      }
    }
    if (!lastResult) {
      const checkRes = await this.request(
        `https://www.googleapis.com/drive/v3/files/${isUpdate ? targetId : "root"}?fields=id,name,mimeType,size,modifiedTime`
      );
      return checkRes.json;
    }
    return lastResult;
  }
  /**
   * Queries Google Drive for the last byte successfully received in an interrupted resumable session.
   */
  async queryResumableStatus(sessionUri, totalBytes) {
    try {
      const res = await (0, import_obsidian2.requestUrl)({
        url: sessionUri,
        method: "PUT",
        headers: {
          "Content-Range": `bytes */${totalBytes}`
        },
        body: new ArrayBuffer(0),
        throw: false
      });
      if (res.status === 308) {
        const rangeHeader = res.headers["range"] || res.headers["Range"];
        if (rangeHeader) {
          const match = /bytes=0-(\d+)/.exec(rangeHeader);
          if (match && match[1]) {
            return parseInt(match[1], 10) + 1;
          }
        }
        return 0;
      }
      return null;
    } catch (e) {
      return null;
    }
  }
  /**
   * Downloads binary file data directly from Google Drive into an ArrayBuffer.
   */
  async downloadFileContent(fileId) {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
    const res = await this.request(url, { method: "GET" });
    return res.arrayBuffer || new ArrayBuffer(0);
  }
  /**
   * Moves a file or folder to Google Drive Trash.
   */
  async trashFile(fileId) {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}`;
    await this.request(url, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ trashed: true })
    });
  }
};

// src/sync/offlineTracker.ts
var import_obsidian3 = require("obsidian");
var OfflineTracker = class {
  constructor(getSettings, saveSettings, onStatusChange) {
    this.getSettings = getSettings;
    this.saveSettings = saveSettings;
    this.onStatusChange = onStatusChange;
    this.isOnline = navigator.onLine;
    this.registerEventListeners();
  }
  registerEventListeners() {
    window.addEventListener("online", () => {
      this.isOnline = true;
      const settings = this.getSettings();
      const count = settings.pendingOfflineChanges.length;
      if (count > 0) {
        new import_obsidian3.Notice(`Google Drive Sync: Back online! ${count} local changes ready to push.`);
      }
      this.onStatusChange("online");
    });
    window.addEventListener("offline", () => {
      this.isOnline = false;
      this.onStatusChange("offline");
      new import_obsidian3.Notice("Google Drive Sync: Offline Mode. Your edits are saved safely on this device.");
    });
  }
  getOnlineState() {
    return this.isOnline;
  }
  async trackFileModification(path) {
    const settings = this.getSettings();
    if (!settings.pendingOfflineChanges) {
      settings.pendingOfflineChanges = [];
    }
    if (!settings.pendingOfflineChanges.includes(path)) {
      settings.pendingOfflineChanges.push(path);
      await this.saveSettings();
    }
  }
  async trackFileDeletion(path) {
    const settings = this.getSettings();
    if (!settings.pendingDeletedPaths) {
      settings.pendingDeletedPaths = [];
    }
    if (!settings.pendingDeletedPaths.includes(path)) {
      settings.pendingDeletedPaths.push(path);
    }
    if (settings.pendingOfflineChanges) {
      const idx = settings.pendingOfflineChanges.indexOf(path);
      if (idx !== -1) {
        settings.pendingOfflineChanges.splice(idx, 1);
      }
    }
    await this.saveSettings();
  }
  async clearPendingChanges() {
    const settings = this.getSettings();
    settings.pendingOfflineChanges = [];
    settings.pendingDeletedPaths = [];
    await this.saveSettings();
  }
};

// src/sync/manualSyncEngine.ts
var import_obsidian4 = require("obsidian");

// src/gdrive/folderTree.ts
var FolderTreeManager = class {
  constructor(client, getVaultRootId, setVaultRootId, getVaultName) {
    this.client = client;
    this.getVaultRootId = getVaultRootId;
    this.setVaultRootId = setVaultRootId;
    this.getVaultName = getVaultName;
    // In-memory cache mapping relative folder path (e.g. "Daily/Notes") -> Google Drive Folder ID
    this.folderIdCache = /* @__PURE__ */ new Map();
    // In-flight mutex locks preventing concurrent duplicate folder creation
    this.inFlightFolderCreation = /* @__PURE__ */ new Map();
  }
  clearCache() {
    this.folderIdCache.clear();
    this.inFlightFolderCreation.clear();
  }
  getCachedFolderId(relativePath) {
    const clean = relativePath.replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
    return this.folderIdCache.get(clean);
  }
  /**
   * Returns a valid root vault folder ID, creating the My Drive/VaultGlide/<VaultName> folder
   * on Google Drive automatically if not already set.
   */
  async getOrEnsureRootId() {
    let rootId = this.getVaultRootId();
    if (rootId) return rootId;
    const vaultName = this.getVaultName() || "DefaultVault";
    const { vaultFolderId } = await this.client.ensureVaultRootFolder(vaultName);
    await this.setVaultRootId(vaultFolderId);
    return vaultFolderId;
  }
  /**
   * Recursively resolves or creates the Google Drive folder hierarchy for a relative path.
   * Uses in-flight promise deduplication to guarantee zero duplicate folders during parallel file uploads.
   */
  async ensureFolderPath(relativePath) {
    const rootId = await this.getOrEnsureRootId();
    const parts = relativePath.split("/").filter(Boolean);
    parts.pop();
    if (parts.length === 0) {
      return rootId;
    }
    let currentParentId = rootId;
    let currentPath = "";
    for (const segment of parts) {
      currentPath = currentPath ? `${currentPath}/${segment}` : segment;
      if (this.folderIdCache.has(currentPath)) {
        currentParentId = this.folderIdCache.get(currentPath);
        continue;
      }
      if (this.inFlightFolderCreation.has(currentPath)) {
        currentParentId = await this.inFlightFolderCreation.get(currentPath);
        continue;
      }
      const creationPromise = this.resolveOrCreateSegment(segment, currentPath, currentParentId);
      this.inFlightFolderCreation.set(currentPath, creationPromise);
      try {
        currentParentId = await creationPromise;
      } finally {
        this.inFlightFolderCreation.delete(currentPath);
      }
    }
    return currentParentId;
  }
  async resolveOrCreateSegment(segment, currentPath, parentId) {
    const children = await this.client.listFolderChildren(parentId);
    const existingFolder = children.find(
      (c) => c.name === segment && c.mimeType === "application/vnd.google-apps.folder"
    );
    if (existingFolder) {
      this.folderIdCache.set(currentPath, existingFolder.id);
      return existingFolder.id;
    }
    const newFolderId = await this.client.createFolder(segment, parentId);
    this.folderIdCache.set(currentPath, newFolderId);
    return newFolderId;
  }
  /**
   * Recursively scans and indexes all files in the remote vault folder into a flat Map<relativePath, RemoteDriveFile>.
   */
  async scanRemoteVaultTree(rootFolderId) {
    const effectiveRootId = rootFolderId || await this.getOrEnsureRootId();
    const fileMap = /* @__PURE__ */ new Map();
    const traverse = async (folderId, currentPathPrefix) => {
      const items = await this.client.listFolderChildren(folderId);
      for (const item of items) {
        const itemRelativePath = currentPathPrefix ? `${currentPathPrefix}/${item.name}` : item.name;
        if (item.mimeType === "application/vnd.google-apps.folder") {
          this.folderIdCache.set(itemRelativePath, item.id);
          await traverse(item.id, itemRelativePath);
        } else {
          fileMap.set(itemRelativePath, item);
        }
      }
    };
    await traverse(effectiveRootId, "");
    return fileMap;
  }
};

// src/sync/configSyncFilter.ts
function isConfigDirFile(path, configDir = ".obsidian") {
  const cleanPath = path.replace(/\\/g, "/").replace(/^\/+/, "");
  const cleanConfig = configDir.replace(/\\/g, "/").replace(/^\/+/, "").replace(/\/+$/, "");
  return cleanPath === cleanConfig || cleanPath.startsWith(`${cleanConfig}/`) || cleanPath.startsWith(".obsidian/");
}
function getRelativeConfigSubpath(path, configDir = ".obsidian") {
  const cleanPath = path.replace(/\\/g, "/").replace(/^\/+/, "");
  const cleanConfig = configDir.replace(/\\/g, "/").replace(/^\/+/, "").replace(/\/+$/, "");
  if (cleanPath.startsWith(`${cleanConfig}/`)) {
    return cleanPath.substring(cleanConfig.length + 1);
  }
  if (cleanPath.startsWith(".obsidian/")) {
    return cleanPath.substring(".obsidian/".length);
  }
  return cleanPath;
}
function shouldSyncConfigFile(path, configDir = ".obsidian", settings) {
  if (!settings.syncConfigDir) {
    return false;
  }
  const subpath = getRelativeConfigSubpath(path, configDir).toLowerCase();
  if (subpath === "plugins/vaultglide/data.json" || subpath === "plugins/obsidian-google-drive/data.json" || subpath.startsWith("plugins/vaultglide/data.") || subpath.startsWith("plugins/obsidian-google-drive/data.")) {
    return false;
  }
  if (subpath.startsWith("cache/") || subpath.startsWith(".trash/") || subpath.endsWith(".ds_store") || subpath.endsWith("thumbs.db") || subpath.endsWith(".tmp") || subpath.endsWith("~")) {
    return false;
  }
  if (subpath === "workspace.json" || subpath === "workspace-mobile.json") {
    return Boolean(settings.syncWorkspaceLayout);
  }
  if (subpath === "graph.json") {
    return false;
  }
  if (subpath === "appearance.json" || subpath.startsWith("snippets/") || subpath.startsWith("themes/")) {
    return Boolean(settings.syncAppearance);
  }
  if (subpath === "community-plugins.json" || subpath === "core-plugins.json" || subpath.startsWith("plugins/")) {
    return Boolean(settings.syncCommunityPlugins);
  }
  if (subpath === "app.json" || subpath === "hotkeys.json" || subpath === "types.json") {
    return Boolean(settings.syncCoreSettings);
  }
  if (!subpath.includes("/") && subpath.endsWith(".json")) {
    return Boolean(settings.syncCoreSettings);
  }
  return false;
}
function isPluginOrThemeFile(path, configDir = ".obsidian") {
  if (!isConfigDirFile(path, configDir)) return false;
  const subpath = getRelativeConfigSubpath(path, configDir).toLowerCase();
  return subpath.startsWith("plugins/") || subpath === "community-plugins.json" || subpath === "appearance.json" || subpath.startsWith("snippets/") || subpath.startsWith("themes/");
}

// src/sync/localHasher.ts
var DEFAULT_IGNORED_PATTERNS = [
  "^.git($|/)",
  "^node_modules($|/)",
  "^.trash($|/)",
  "^.DS_Store$",
  "^Thumbs.db$",
  "~$",
  ".tmp$"
];
var LocalHasher = class {
  constructor(vault, getSettings) {
    this.vault = vault;
    this.getSettings = getSettings;
  }
  /**
   * Computes SHA-256 hex string for binary buffer using Web Crypto API.
   */
  async computeHash(buffer) {
    const hashBuffer = await crypto.subtle.digest("SHA-256", buffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  /**
   * Checks if a file path is ignored from syncing.
   * - Config dir (.obsidian) paths are checked against granular user settings & blacklist.
   * - Vault paths are checked against standard ignore patterns & custom user patterns.
   */
  isIgnored(path) {
    const clean = path.replace(/\\/g, "/").replace(/^\/+/, "");
    const configDir = this.vault.configDir || ".obsidian";
    if (isConfigDirFile(clean, configDir)) {
      const settings = this.getSettings();
      return !shouldSyncConfigFile(clean, configDir, settings);
    }
    const custom = this.getSettings().customIgnoredPatterns || [];
    const all = [...DEFAULT_IGNORED_PATTERNS, ...custom];
    for (const pat of all) {
      try {
        const reg = new RegExp(pat, "i");
        if (reg.test(clean)) return true;
      } catch (e) {
      }
    }
    return false;
  }
  /**
   * Recursively discovers all files in Obsidian's hidden config directory (e.g. .obsidian).
   */
  async scanConfigDir(configDir) {
    const collected = [];
    const queue = [configDir];
    while (queue.length > 0) {
      const current = queue.shift();
      try {
        const list = await this.vault.adapter.list(current);
        if (list.files) {
          for (const f of list.files) {
            collected.push(f.replace(/\\/g, "/").replace(/^\/+/, ""));
          }
        }
        if (list.folders) {
          for (const d of list.folders) {
            queue.push(d.replace(/\\/g, "/").replace(/^\/+/, ""));
          }
        }
      } catch (e) {
      }
    }
    return collected;
  }
  /**
   * Scans all non-ignored vault files and eligible .obsidian config files,
   * computing their hashes in parallel chunks.
   */
  async scanVault() {
    const settings = this.getSettings();
    const configDir = this.vault.configDir || ".obsidian";
    const result = [];
    const vaultFiles = this.vault.getFiles();
    const validVaultFiles = vaultFiles.filter((f) => !this.isIgnored(f.path));
    const BATCH_SIZE = 50;
    for (let i = 0; i < validVaultFiles.length; i += BATCH_SIZE) {
      const batch = validVaultFiles.slice(i, i + BATCH_SIZE);
      const batchEntries = await Promise.all(
        batch.map(async (file) => {
          try {
            const data = await this.vault.readBinary(file);
            const hash = await this.computeHash(data);
            return {
              relativePath: file.path.replace(/\\/g, "/").replace(/^\/+/, ""),
              hash,
              size: file.stat.size,
              mtime: file.stat.mtime
            };
          } catch (e) {
            return null;
          }
        })
      );
      for (const entry of batchEntries) {
        if (entry) result.push(entry);
      }
    }
    if (settings.syncConfigDir) {
      const configPaths = await this.scanConfigDir(configDir);
      const eligibleConfigPaths = configPaths.filter((p) => shouldSyncConfigFile(p, configDir, settings));
      for (let i = 0; i < eligibleConfigPaths.length; i += BATCH_SIZE) {
        const batch = eligibleConfigPaths.slice(i, i + BATCH_SIZE);
        const batchEntries = await Promise.all(
          batch.map(async (path) => {
            try {
              const data = await this.vault.adapter.readBinary(path);
              const stat = await this.vault.adapter.stat(path);
              const hash = await this.computeHash(data);
              return {
                relativePath: path,
                hash,
                size: (stat == null ? void 0 : stat.size) || data.byteLength,
                mtime: (stat == null ? void 0 : stat.mtime) || Date.now()
              };
            } catch (e) {
              return null;
            }
          })
        );
        for (const entry of batchEntries) {
          if (entry) result.push(entry);
        }
      }
    }
    return result;
  }
};

// src/sync/manualSyncEngine.ts
var ManualSyncEngine = class {
  constructor(app, getSettings, loadSettings, saveSettings, client, offlineTracker, statusBar) {
    this.app = app;
    this.getSettings = getSettings;
    this.loadSettings = loadSettings;
    this.saveSettings = saveSettings;
    this.client = client;
    this.offlineTracker = offlineTracker;
    this.statusBar = statusBar;
    this.hasher = new LocalHasher(app.vault, () => this.getSettings());
    this.folderTree = new FolderTreeManager(
      client,
      () => this.getSettings().vaultFolderId,
      async (id) => {
        const settings = this.getSettings();
        settings.vaultFolderId = id;
        await this.saveSettings();
      },
      () => this.getSettings().vaultName
    );
  }
  /**
   * PUSH: High-Speed Parallel Upload of local vault changes directly to Google Drive.
   * Modifies existing files in-place with zero duplicate creations.
   */
  async push() {
    var _a, _b, _c, _d;
    await this.loadSettings();
    const settings = this.getSettings();
    settings.syncedFileHashes = settings.syncedFileHashes || {};
    if (!settings.accessToken) {
      new import_obsidian4.Notice("Google Drive Sync: Please log in or pair device in plugin settings.");
      this.statusBar.setStatus("unauthenticated");
      return;
    }
    if (!navigator.onLine) {
      new import_obsidian4.Notice("Google Drive Sync: You are offline. Changes remain saved locally.");
      this.statusBar.setStatus("offline", `${settings.pendingOfflineChanges.length} pending`);
      return;
    }
    this.statusBar.setStatus("syncing", "Scanning...");
    new import_obsidian4.Notice("Google Drive Sync: Checking vault changes...");
    try {
      const rootFolderId = await this.folderTree.getOrEnsureRootId();
      const [localFiles, remoteMap] = await Promise.all([
        this.hasher.scanVault(),
        this.folderTree.scanRemoteVaultTree(rootFolderId)
      ]);
      const toUpload = [];
      const localPathSet = /* @__PURE__ */ new Set();
      for (const local of localFiles) {
        const cleanPath = local.relativePath.replace(/\\/g, "/").replace(/^\/+/, "");
        localPathSet.add(cleanPath);
        const remote = remoteMap.get(cleanPath);
        if (!remote) {
          toUpload.push({ local });
        } else {
          const remoteSize = remote.size !== void 0 ? parseInt(remote.size, 10) : 0;
          const cachedHash = settings.syncedFileHashes[cleanPath];
          if (cachedHash && cachedHash === local.hash && remoteSize === local.size) {
            continue;
          }
          if (remoteSize === local.size && !cachedHash) {
            const remoteTime = remote.modifiedTime ? new Date(remote.modifiedTime).getTime() : 0;
            if (local.mtime <= remoteTime + 1e3) {
              settings.syncedFileHashes[cleanPath] = local.hash;
              continue;
            }
          }
          toUpload.push({ local, remote });
        }
      }
      const deletedToTrash = [];
      const pendingDeletions = new Set(settings.pendingDeletedPaths || []);
      for (const trackedPath of Object.keys(settings.syncedFileHashes)) {
        if (!localPathSet.has(trackedPath)) {
          pendingDeletions.add(trackedPath);
        }
      }
      const pendingDeletionList = Array.from(pendingDeletions);
      const lastSyncMs = settings.lastSyncTime ? new Date(settings.lastSyncTime).getTime() : 0;
      for (const [remotePath, remoteFile] of remoteMap.entries()) {
        if (this.hasher.isIgnored(remotePath)) {
          continue;
        }
        if (localPathSet.has(remotePath)) {
          continue;
        }
        const isExplicitlyDeleted = pendingDeletions.has(remotePath) || pendingDeletionList.some((p) => remotePath === p || remotePath.startsWith(p.endsWith("/") ? p : `${p}/`));
        const isPreviouslyTracked = remotePath in settings.syncedFileHashes;
        const remoteModMs = remoteFile.modifiedTime ? new Date(remoteFile.modifiedTime).getTime() : 0;
        const existedAtLastSync = lastSyncMs > 0 && remoteModMs <= lastSyncMs + 1e4;
        if (isExplicitlyDeleted || isPreviouslyTracked || existedAtLastSync) {
          deletedToTrash.push({ path: remotePath, remoteFile });
        }
      }
      const deletedFoldersToTrash = [];
      for (const delPath of pendingDeletionList) {
        const folderId = this.folderTree.getCachedFolderId(delPath);
        if (folderId && !Array.from(localPathSet).some((lp) => lp.startsWith(delPath.endsWith("/") ? delPath : `${delPath}/`))) {
          deletedFoldersToTrash.push({ path: delPath, folderId });
        }
      }
      if (toUpload.length === 0 && deletedToTrash.length === 0 && deletedFoldersToTrash.length === 0) {
        new import_obsidian4.Notice("Google Drive Sync: Everything is up to date. Nothing to push.");
        settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
        settings.lastSyncStatus = "up-to-date";
        await this.saveSettings();
        await this.offlineTracker.clearPendingChanges();
        this.statusBar.setStatus("up-to-date");
        return;
      }
      let trashedCount = 0;
      if (deletedToTrash.length > 0 || deletedFoldersToTrash.length > 0) {
        const totalToDelete = deletedToTrash.length + deletedFoldersToTrash.length;
        this.statusBar.setStatus("syncing", `Trashing ${totalToDelete} item(s)...`);
        for (const item of deletedToTrash) {
          try {
            await this.client.trashFile(item.remoteFile.id);
            delete settings.syncedFileHashes[item.path];
            trashedCount++;
          } catch (delErr) {
            console.warn(`Could not trash remote file ${item.path}:`, delErr);
          }
        }
        for (const fItem of deletedFoldersToTrash) {
          try {
            await this.client.trashFile(fItem.folderId);
            trashedCount++;
          } catch (delErr) {
            console.warn(`Could not trash remote folder ${fItem.path}:`, delErr);
          }
        }
        for (const trackedPath of Object.keys(settings.syncedFileHashes)) {
          if (!localPathSet.has(trackedPath) && !remoteMap.has(trackedPath)) {
            delete settings.syncedFileHashes[trackedPath];
          }
        }
      }
      const uniqueFolders = Array.from(
        new Set(
          toUpload.map((item) => {
            const parts = item.local.relativePath.replace(/\\/g, "/").split("/").filter(Boolean);
            parts.pop();
            return parts.join("/");
          })
        )
      ).filter(Boolean);
      if (uniqueFolders.length > 0) {
        this.statusBar.setStatus("syncing", "Preparing folders...");
        await Promise.all(uniqueFolders.map((p) => this.folderTree.ensureFolderPath(`${p}/placeholder.md`)));
      }
      let uploadedCount = 0;
      const total = toUpload.length;
      const CONCURRENCY_BATCH = 10;
      for (let i = 0; i < total; i += CONCURRENCY_BATCH) {
        const batch = toUpload.slice(i, i + CONCURRENCY_BATCH);
        await Promise.all(
          batch.map(async (item) => {
            const cleanPath = item.local.relativePath.replace(/\\/g, "/").replace(/^\/+/, "");
            const binaryData = await this.readLocalFileBinary(cleanPath);
            if (binaryData) {
              const mimeType = this.getMimeType(cleanPath);
              const onProgress = item.local.size > 5 * 1024 * 1024 ? (uploadedBytes, totalBytes) => {
                const pct = Math.round(uploadedBytes / totalBytes * 100);
                const filename = cleanPath.split("/").pop();
                this.statusBar.setStatus("syncing", `${filename} (${pct}%)`);
              } : void 0;
              if (item.remote) {
                await this.client.updateFileContent(item.remote.id, mimeType, binaryData, onProgress);
              } else {
                const parentFolderId = await this.folderTree.ensureFolderPath(cleanPath);
                const filename = cleanPath.split("/").pop();
                await this.client.uploadNewFile(filename, parentFolderId, mimeType, binaryData, onProgress);
              }
              settings.syncedFileHashes[cleanPath] = item.local.hash;
              uploadedCount++;
              this.statusBar.setStatus("syncing", `${uploadedCount}/${total}`);
            }
          })
        );
      }
      settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
      settings.lastSyncStatus = "up-to-date";
      await this.saveSettings();
      await this.offlineTracker.clearPendingChanges();
      this.statusBar.setStatus("up-to-date");
      let noticeMsg = `Google Drive Sync: Successfully pushed ${uploadedCount} file(s) to Drive!`;
      if (uploadedCount > 0 && trashedCount > 0) {
        noticeMsg = `Google Drive Sync: Uploaded ${uploadedCount} file(s), moved ${trashedCount} deleted file(s) to Drive trash!`;
      } else if (trashedCount > 0) {
        noticeMsg = `Google Drive Sync: Moved ${trashedCount} deleted file(s) to Drive trash!`;
      }
      new import_obsidian4.Notice(noticeMsg);
    } catch (err) {
      const isOffline = ((_a = err.message) == null ? void 0 : _a.includes("NETWORK_OFFLINE")) || ((_b = err.message) == null ? void 0 : _b.includes("UnknownHostException")) || ((_c = err.message) == null ? void 0 : _c.includes("ENOTFOUND")) || ((_d = err.message) == null ? void 0 : _d.includes("Failed to fetch"));
      if (isOffline) {
        settings.lastSyncStatus = "offline";
        await this.saveSettings();
        this.statusBar.setStatus("offline");
        new import_obsidian4.Notice("Google Drive Sync: No internet connection. Please check your network and try again.");
        return;
      }
      console.error("Push Error:", err);
      settings.lastSyncStatus = "failed";
      await this.saveSettings();
      this.statusBar.setStatus("failed");
      new import_obsidian4.Notice(`Google Drive Push failed: ${err.message}`);
    }
  }
  /**
   * PULL: Downloads cloud vault changes directly from Google Drive.
   */
  async pull() {
    var _a, _b, _c, _d;
    await this.loadSettings();
    const settings = this.getSettings();
    settings.syncedFileHashes = settings.syncedFileHashes || {};
    if (!settings.accessToken) {
      new import_obsidian4.Notice("Google Drive Sync: Please log in or pair device in plugin settings.");
      this.statusBar.setStatus("unauthenticated");
      return;
    }
    if (!navigator.onLine) {
      new import_obsidian4.Notice("Google Drive Sync: You are offline.");
      this.statusBar.setStatus("offline");
      return;
    }
    this.statusBar.setStatus("syncing", "Scanning cloud...");
    new import_obsidian4.Notice("Google Drive Sync: Checking Google Drive for changes...");
    try {
      const rootFolderId = await this.folderTree.getOrEnsureRootId();
      const [localFiles, remoteMap] = await Promise.all([
        this.hasher.scanVault(),
        this.folderTree.scanRemoteVaultTree(rootFolderId)
      ]);
      const localMap = /* @__PURE__ */ new Map();
      for (const lf of localFiles) {
        localMap.set(lf.relativePath.replace(/\\/g, "/").replace(/^\/+/, ""), lf);
      }
      const remotePathSet = new Set(remoteMap.keys());
      let localTrashedCount = 0;
      const configDir = this.app.vault.configDir || ".obsidian";
      for (const trackedPath of Object.keys(settings.syncedFileHashes)) {
        if (!remotePathSet.has(trackedPath) && localMap.has(trackedPath)) {
          if (!settings.pendingDeletedPaths || !settings.pendingDeletedPaths.includes(trackedPath)) {
            try {
              if (isConfigDirFile(trackedPath, configDir)) {
                if (await this.app.vault.adapter.exists(trackedPath)) {
                  await this.app.vault.adapter.remove(trackedPath);
                  delete settings.syncedFileHashes[trackedPath];
                  localTrashedCount++;
                }
              } else {
                const abstractFile = this.app.vault.getAbstractFileByPath(trackedPath);
                if (abstractFile instanceof import_obsidian4.TFile) {
                  await this.app.vault.trash(abstractFile, true);
                  delete settings.syncedFileHashes[trackedPath];
                  localTrashedCount++;
                }
              }
            } catch (trashErr) {
              console.warn(`Could not trash local file ${trackedPath}:`, trashErr);
            }
          }
        }
      }
      const toDownload = [];
      for (const [remotePath, remoteFile] of remoteMap.entries()) {
        if (this.hasher.isIgnored(remotePath)) {
          continue;
        }
        const local = localMap.get(remotePath);
        const remoteSize = remoteFile.size !== void 0 ? parseInt(remoteFile.size, 10) : 0;
        const cachedHash = settings.syncedFileHashes[remotePath];
        if (!local) {
          const isPendingDeleted = settings.pendingDeletedPaths && settings.pendingDeletedPaths.some((p) => remotePath === p || remotePath.startsWith(p.endsWith("/") ? p : `${p}/`));
          if (isPendingDeleted) {
            continue;
          }
          toDownload.push(remoteFile);
        } else {
          const isSizeDifferent = remoteSize !== local.size;
          const remoteTime = remoteFile.modifiedTime ? new Date(remoteFile.modifiedTime).getTime() : 0;
          const isRemoteNewer = remoteTime > local.mtime + 2e3;
          const isContentMismatch = cachedHash ? cachedHash !== local.hash : true;
          if (isSizeDifferent || isRemoteNewer && isContentMismatch) {
            toDownload.push(remoteFile);
          }
        }
      }
      if (toDownload.length === 0 && localTrashedCount === 0) {
        new import_obsidian4.Notice("Google Drive Sync: Your vault is already up to date with Google Drive.");
        settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
        settings.lastSyncStatus = "up-to-date";
        await this.saveSettings();
        this.statusBar.setStatus("up-to-date");
        return;
      }
      let downloadedCount = 0;
      let hasUpdatedPluginsOrThemes = false;
      const total = toDownload.length;
      for (const remoteFile of toDownload) {
        const relPath = this.getRelativePathForRemote(remoteFile, remoteMap);
        const data = await this.client.downloadFileContent(remoteFile.id);
        await this.writeLocalFileBinary(relPath, data);
        if (isPluginOrThemeFile(relPath, configDir)) {
          hasUpdatedPluginsOrThemes = true;
        }
        const newHash = await this.hasher.computeHash(data);
        settings.syncedFileHashes[relPath] = newHash;
        downloadedCount++;
        this.statusBar.setStatus("syncing", `Pulling ${downloadedCount}/${total}`);
      }
      settings.lastSyncTime = (/* @__PURE__ */ new Date()).toISOString();
      settings.lastSyncStatus = "up-to-date";
      await this.saveSettings();
      this.statusBar.setStatus("up-to-date");
      let pullMsg = `Google Drive Sync: Successfully downloaded ${downloadedCount} note(s)!`;
      if (downloadedCount > 0 && localTrashedCount > 0) {
        pullMsg = `Google Drive Sync: Downloaded ${downloadedCount} note(s), removed ${localTrashedCount} remote-deleted item(s).`;
      } else if (localTrashedCount > 0) {
        pullMsg = `Google Drive Sync: Removed ${localTrashedCount} remote-deleted item(s).`;
      }
      new import_obsidian4.Notice(pullMsg);
      if (hasUpdatedPluginsOrThemes) {
        new import_obsidian4.Notice("Google Drive Sync: Plugins or themes were updated. Reload Obsidian (Ctrl/Cmd + R) to activate them.", 8e3);
      }
    } catch (err) {
      const isOffline = ((_a = err.message) == null ? void 0 : _a.includes("NETWORK_OFFLINE")) || ((_b = err.message) == null ? void 0 : _b.includes("UnknownHostException")) || ((_c = err.message) == null ? void 0 : _c.includes("ENOTFOUND")) || ((_d = err.message) == null ? void 0 : _d.includes("Failed to fetch"));
      if (isOffline) {
        settings.lastSyncStatus = "offline";
        await this.saveSettings();
        this.statusBar.setStatus("offline");
        new import_obsidian4.Notice("Google Drive Sync: No internet connection. Please check your network and try again.");
        return;
      }
      console.error("Pull Error:", err);
      settings.lastSyncStatus = "failed";
      await this.saveSettings();
      this.statusBar.setStatus("failed");
      new import_obsidian4.Notice(`Google Drive Pull failed: ${err.message}`);
    }
  }
  /**
   * Safely reads binary content from either regular vault files or hidden .obsidian config files.
   */
  async readLocalFileBinary(cleanPath) {
    try {
      const configDir = this.app.vault.configDir || ".obsidian";
      if (isConfigDirFile(cleanPath, configDir)) {
        const buffer = await this.app.vault.adapter.readBinary(cleanPath);
        return new Uint8Array(buffer);
      }
      const abstractFile = this.app.vault.getAbstractFileByPath(cleanPath);
      if (abstractFile instanceof import_obsidian4.TFile) {
        const buffer = await this.app.vault.readBinary(abstractFile);
        return new Uint8Array(buffer);
      }
      if (await this.app.vault.adapter.exists(cleanPath)) {
        const buffer = await this.app.vault.adapter.readBinary(cleanPath);
        return new Uint8Array(buffer);
      }
      return null;
    } catch (e) {
      console.warn(`Failed to read local binary file ${cleanPath}:`, e);
      return null;
    }
  }
  /**
   * Safely writes binary content to either regular vault files or hidden .obsidian config files.
   */
  async writeLocalFileBinary(relativePath, data) {
    await this.ensureLocalParentDir(relativePath);
    const configDir = this.app.vault.configDir || ".obsidian";
    const arrayBuffer = data instanceof Uint8Array ? data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) : data;
    if (isConfigDirFile(relativePath, configDir)) {
      await this.app.vault.adapter.writeBinary(relativePath, arrayBuffer);
      return;
    }
    const existing = this.app.vault.getAbstractFileByPath(relativePath);
    if (existing instanceof import_obsidian4.TFile) {
      await this.app.vault.modifyBinary(existing, arrayBuffer);
    } else {
      try {
        await this.app.vault.createBinary(relativePath, arrayBuffer);
      } catch (e) {
        await this.app.vault.adapter.writeBinary(relativePath, arrayBuffer);
      }
    }
  }
  getRelativePathForRemote(targetFile, remoteMap) {
    for (const [path, file] of remoteMap.entries()) {
      if (file.id === targetFile.id) return path;
    }
    return targetFile.name;
  }
  async ensureLocalParentDir(relativePath) {
    const parts = relativePath.replace(/\\/g, "/").split("/").filter(Boolean);
    parts.pop();
    if (parts.length === 0) return;
    const configDir = this.app.vault.configDir || ".obsidian";
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const isConfig = isConfigDirFile(current, configDir);
      const exists = isConfig ? await this.app.vault.adapter.exists(current) : this.app.vault.getAbstractFileByPath(current) !== null;
      if (!exists) {
        try {
          if (isConfig) {
            await this.app.vault.adapter.mkdir(current);
          } else {
            await this.app.vault.createFolder(current);
          }
        } catch (e) {
          try {
            await this.app.vault.adapter.mkdir(current);
          } catch (e2) {
          }
        }
      }
    }
  }
  getMimeType(path) {
    if (path.endsWith(".md")) return "text/markdown; charset=UTF-8";
    if (path.endsWith(".png")) return "image/png";
    if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
    if (path.endsWith(".pdf")) return "application/pdf";
    if (path.endsWith(".json") || path.endsWith(".canvas")) return "application/json";
    if (path.endsWith(".css")) return "text/css";
    if (path.endsWith(".js")) return "application/javascript";
    return "application/octet-stream";
  }
};

// src/ui/statusBar.ts
var StatusBarController = class {
  constructor(statusBarEl) {
    this.statusBarEl = statusBarEl;
  }
  setStatus(state, extraInfo) {
    let icon = "\u2601\uFE0F";
    let text = "Drive";
    switch (state) {
      case "up-to-date":
        icon = "\u{1F7E2}";
        text = "Drive: Up to date";
        break;
      case "local-changes":
        icon = "\u{1F535}";
        text = "Drive: Local Changes";
        break;
      case "cloud-newer":
        icon = "\u{1F7E1}";
        text = "Drive: Cloud Newer";
        break;
      case "syncing":
        icon = "\u23F3";
        text = extraInfo ? `Drive: ${extraInfo}` : "Drive: Syncing...";
        break;
      case "offline":
        icon = "\u{1F4E1}";
        text = extraInfo ? `Drive: Offline (${extraInfo})` : "Drive: Offline";
        break;
      case "failed":
        icon = "\u{1F534}";
        text = "Drive: Sync Failed";
        break;
      case "unauthenticated":
        icon = "\u26AA";
        text = "Drive: Not Connected";
        break;
    }
    this.statusBarEl.setText(`${icon} ${text}`);
    this.statusBarEl.setAttribute("title", `Obsidian Google Drive Sync: ${text}`);
  }
};

// src/ui/settingsTab.ts
var import_obsidian5 = require("obsidian");
var GoogleDriveSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VaultGlide \u2014 Google Drive Sync" });
    containerEl.createEl("p", {
      text: "Private, direct manual cloud synchronization using your personal Google Drive account. Zero third-party storage.",
      cls: "setting-item-description"
    });
    const isConnected = Boolean(this.plugin.settings.accessToken);
    const isSessionExpired = this.plugin.settings.lastSyncStatus === "unauthenticated";
    if (!isConnected) {
      const connectSetting = new import_obsidian5.Setting(containerEl).setName("Connection Status: Not Connected").setDesc("Connect your personal Google Drive via the VaultGlide web portal to sync your notes across devices.").addButton(
        (btn) => btn.setButtonText("Connect with VaultGlide").setCta().onClick(() => {
          const targetUrl = this.plugin.settings.serverRelayUrl || "http://localhost:5180";
          window.open(targetUrl, "_blank");
          new import_obsidian5.Notice("Opening VaultGlide Web Portal in your browser...");
        })
      );
      connectSetting.settingEl.style.border = "1px solid var(--background-modifier-border)";
      connectSetting.settingEl.style.borderRadius = "8px";
      connectSetting.settingEl.style.padding = "12px";
      connectSetting.settingEl.style.marginBottom = "16px";
    } else if (isSessionExpired) {
      const expiredSetting = new import_obsidian5.Setting(containerEl).setName("\u26A0\uFE0F Session Expired / Re-authentication Needed").setDesc(`Your Google Drive token for ${this.plugin.settings.userEmail || "account"} needs to be renewed.`).addButton(
        (btn) => btn.setButtonText("Re-authenticate on Web").setWarning().onClick(() => {
          const targetUrl = this.plugin.settings.serverRelayUrl || "http://localhost:5180";
          window.open(targetUrl, "_blank");
          new import_obsidian5.Notice("Opening VaultGlide to renew connection...");
        })
      ).addButton(
        (btn) => btn.setButtonText("Disconnect").onClick(async () => {
          await this.handleDisconnect();
        })
      );
      expiredSetting.settingEl.style.border = "1px solid var(--text-warning)";
      expiredSetting.settingEl.style.borderRadius = "8px";
      expiredSetting.settingEl.style.padding = "12px";
      expiredSetting.settingEl.style.marginBottom = "16px";
    } else {
      const connectedSetting = new import_obsidian5.Setting(containerEl).setName(`\u{1F7E2} Connected: ${this.plugin.settings.userEmail || "Google User"}`).setDesc(`Cloud Vault: Google Drive/VaultGlide/${this.plugin.settings.vaultName}`).addButton(
        (btn) => btn.setButtonText("Push Notes").setCta().onClick(async () => {
          await this.plugin.syncEngine.push();
        })
      ).addButton(
        (btn) => btn.setButtonText("Pull Notes").onClick(async () => {
          await this.plugin.syncEngine.pull();
        })
      ).addButton(
        (btn) => btn.setButtonText("Disconnect").setWarning().onClick(async () => {
          await this.handleDisconnect();
        })
      );
      connectedSetting.settingEl.style.border = "1px solid var(--interactive-accent)";
      connectedSetting.settingEl.style.borderRadius = "8px";
      connectedSetting.settingEl.style.padding = "12px";
      connectedSetting.settingEl.style.marginBottom = "16px";
    }
    containerEl.createEl("h3", { text: "Vault & Storage Settings" });
    new import_obsidian5.Setting(containerEl).setName("Cloud Vault Folder Name").setDesc("Folder created inside your personal Google Drive (My Drive/VaultGlide/<VaultName>)").addText(
      (text) => text.setPlaceholder("MyVault").setValue(this.plugin.settings.vaultName).onChange(async (value) => {
        this.plugin.settings.vaultName = value.trim() || "MyVault";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("VaultGlide Web Portal URL").setDesc("The web companion dashboard URL for web viewing and initial authentication.").addText(
      (text) => text.setPlaceholder("http://localhost:5180").setValue(this.plugin.settings.serverRelayUrl).onChange(async (value) => {
        this.plugin.settings.serverRelayUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Configuration & Plugin Sync (.obsidian)" });
    containerEl.createEl("p", {
      text: "Synchronize Obsidian preferences, themes, and community plugins across your devices via Google Drive.",
      cls: "setting-item-description"
    });
    new import_obsidian5.Setting(containerEl).setName("Sync Configuration & Plugins (.obsidian)").setDesc("Master toggle: Scan and synchronize files inside the .obsidian folder.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncConfigDir).onChange(async (val) => {
        this.plugin.settings.syncConfigDir = val;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.syncConfigDir) {
      new import_obsidian5.Setting(containerEl).setName("Sync Core Settings & Hotkeys").setDesc("Sync general app preferences, file options, and hotkeys (app.json, hotkeys.json).").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.syncCoreSettings).onChange(async (val) => {
          this.plugin.settings.syncCoreSettings = val;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("Sync Themes & CSS Snippets").setDesc("Sync active theme, custom styles, and snippets (appearance.json, snippets/).").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.syncAppearance).onChange(async (val) => {
          this.plugin.settings.syncAppearance = val;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("Sync Community Plugins").setDesc("Sync installed community plugins and settings. (VaultGlide credentials are automatically excluded for safety).").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.syncCommunityPlugins).onChange(async (val) => {
          this.plugin.settings.syncCommunityPlugins = val;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("Sync Workspace Layout (Open Tabs)").setDesc("Sync open tabs and panes (workspace.json). Recommended: OFF if syncing between Desktop and Mobile.").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.syncWorkspaceLayout).onChange(async (val) => {
          this.plugin.settings.syncWorkspaceLayout = val;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h3", { text: "Sync Ignore Rules" });
    new import_obsidian5.Setting(containerEl).setName("Custom Ignored Regex Patterns").setDesc("Enter one regex pattern per line to exclude files/folders from sync (e.g. ^Private/ or \\.secret$)").addTextArea(
      (text) => text.setPlaceholder("^Private/\n\\.secret$").setValue(this.plugin.settings.customIgnoredPatterns.join("\n")).onChange(async (value) => {
        this.plugin.settings.customIgnoredPatterns = value.split("\n").map((s) => s.trim()).filter(Boolean);
        await this.plugin.saveSettings();
      })
    );
  }
  async handleDisconnect() {
    this.plugin.settings.accessToken = "";
    this.plugin.settings.refreshToken = "";
    this.plugin.settings.userEmail = "";
    this.plugin.settings.vaultFolderId = "";
    this.plugin.settings.lastSyncStatus = "unauthenticated";
    await this.plugin.saveSettings();
    this.plugin.statusBar.setStatus("unauthenticated");
    new import_obsidian5.Notice("Disconnected from Google Drive");
    this.display();
  }
};

// src/main.ts
var GoogleDriveSyncPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    const statusBarEl = this.addStatusBarItem();
    this.statusBar = new StatusBarController(statusBarEl);
    this.statusBar.setStatus(this.settings.lastSyncStatus);
    this.auth = new GDriveAuth(
      () => this.settings,
      () => this.saveSettings()
    );
    this.client = new GDriveClient(this.auth);
    this.offlineTracker = new OfflineTracker(
      () => this.settings,
      () => this.saveSettings(),
      (status) => {
        if (status === "offline") {
          this.statusBar.setStatus("offline", `${this.settings.pendingOfflineChanges.length} pending`);
        } else {
          this.statusBar.setStatus(this.settings.lastSyncStatus);
        }
      }
    );
    this.syncEngine = new ManualSyncEngine(
      this.app,
      () => this.settings,
      () => this.loadSettings(),
      () => this.saveSettings(),
      this.client,
      this.offlineTracker,
      this.statusBar
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!navigator.onLine) {
          this.offlineTracker.trackFileModification(file.path);
          this.statusBar.setStatus("offline", `${this.settings.pendingOfflineChanges.length} pending`);
        } else if (this.settings.lastSyncStatus === "up-to-date") {
          this.settings.lastSyncStatus = "local-changes";
          this.statusBar.setStatus("local-changes");
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!navigator.onLine) {
          this.offlineTracker.trackFileModification(file.path);
        } else if (this.settings.lastSyncStatus === "up-to-date") {
          this.settings.lastSyncStatus = "local-changes";
          this.statusBar.setStatus("local-changes");
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        const cleanPath = file.path.replace(/\\/g, "/").replace(/^\/+/, "");
        this.offlineTracker.trackFileDeletion(cleanPath);
        if (this.settings.syncedFileHashes) {
          const folderPrefix = cleanPath.endsWith("/") ? cleanPath : `${cleanPath}/`;
          for (const trackedPath of Object.keys(this.settings.syncedFileHashes)) {
            if (trackedPath.startsWith(folderPrefix)) {
              this.offlineTracker.trackFileDeletion(trackedPath);
            }
          }
        }
        if (this.settings.lastSyncStatus === "up-to-date") {
          this.settings.lastSyncStatus = "local-changes";
          this.statusBar.setStatus("local-changes");
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        const cleanOld = oldPath.replace(/\\/g, "/").replace(/^\/+/, "");
        const cleanNew = file.path.replace(/\\/g, "/").replace(/^\/+/, "");
        this.offlineTracker.trackFileDeletion(cleanOld);
        this.offlineTracker.trackFileModification(cleanNew);
        if (this.settings.syncedFileHashes) {
          const folderOldPrefix = cleanOld.endsWith("/") ? cleanOld : `${cleanOld}/`;
          for (const trackedPath of Object.keys(this.settings.syncedFileHashes)) {
            if (trackedPath.startsWith(folderOldPrefix)) {
              this.offlineTracker.trackFileDeletion(trackedPath);
            }
          }
        }
        if (this.settings.lastSyncStatus === "up-to-date") {
          this.settings.lastSyncStatus = "local-changes";
          this.statusBar.setStatus("local-changes");
        }
      })
    );
    this.addRibbonIcon("upload-cloud", "Push to Google Drive", async () => {
      await this.syncEngine.push();
    });
    this.addRibbonIcon("download-cloud", "Pull from Google Drive", async () => {
      await this.syncEngine.pull();
    });
    this.addCommand({
      id: "gdrive-push",
      name: "Push vault to Google Drive",
      callback: async () => {
        await this.syncEngine.push();
      }
    });
    this.addCommand({
      id: "gdrive-pull",
      name: "Pull vault from Google Drive",
      callback: async () => {
        await this.syncEngine.pull();
      }
    });
    this.addSettingTab(new GoogleDriveSettingTab(this.app, this));
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
